### ISSUE TITLE
Huge cross in pending invites screen

### ISSUE THREAD

**Issue by jamy015** [AreaFiftyLAN/lancie-frontend#249] opened 2016-05-31 15:13 UTC
![capture](https://cloud.githubusercontent.com/assets/3188721/15679652/e4160968-2752-11e6-9167-7b849c6a546e.PNG)

As you can see, there is a huge cross for the second player instead of the smaller cancel cross for the first player.

**Comment by skamoen** [comment] 2016-05-31 15:22
Interesting. Which browser + version is this?

**Comment by jamy015** [comment] 2016-05-31 15:24
This is on Windows 10. Presence of the bug mysteriously differs per browser:
- Chrome 51: behaviour is not present.
- Firefox 46: behaviour is present as in the screenshot.
- Edge 20: behaviour is present and usernames are not even displayed.
- IE 11: behaviour is present for both users (not only the second).

**Comment by martijn9612** [comment] 2016-05-31 16:59
I cannot reproduce this, I think the issue was fixed with my bower update earlier! I will upload a new version soon. You could check whether the issue is still present.

**Closed** 2016-11-06 16:05 UTC
Labels: wontfix
