### ISSUE TITLE
Refactor dialogs

### ISSUE THREAD

**Issue by TimvdLippe** [AreaFiftyLAN/lancie-frontend#343] opened 2016-12-24 12:44 UTC
Apparently our dialogs are causing memory leaks, as well as problems with the z-index requiring us to append the dialog to body. We should fix these issues before launching.

**Comment by martijnjanssen** [comment] 2016-12-24 13:54
Are you sure it is a memory leak? It only takes cpu usage as far as I know.

**Comment by martijnjanssen** [comment] 2017-01-08 14:09
This was an issue involving the 'vimium' chrome extension. This is also a duplicate of #297 .

**Closed by martijnjanssen** 2017-01-08 14:09 UTC
