### ISSUE TITLE
Ability to pay after closing ideal window

### ISSUE THREAD

**Issue by bvanderdrift** [AreaFiftyLAN/lancie-frontend#384] opened 2017-01-09 15:23 UTC
After doing a checkout at the ticket page, and closing the ideal page, I can't finish the payment for my pending order. It does show up at the orders component on the My Area page, but there is no button for paying while it is pending.

**Comment by TimvdLippe** [comment] 2017-01-09 15:26
I think this is a duplicate of https://github.com/AreaFiftyLAN/lancie-frontend/issues/93

**Comment by martijnjanssen** [comment] 2017-04-05 10:01
Duplicate indeed

**Closed by martijnjanssen** 2017-04-05 10:01 UTC
