### ISSUE TITLE
Missing ajax headers when using auto-login

### ISSUE THREAD

**Issue by svenpopping** [AreaFiftyLAN/lancie-frontend#16] opened 2016-01-16 19:10 UTC

**Comment by TimvdLippe** [comment] 2016-01-17 12:44
I am unable to reproduce this issue on current master. Can you provide reproduction steps?

**Comment by svenpopping** [comment] 2016-01-17 13:48
Go to ticket -> Login -> Add ticket and it shows up in the cart. Then close the tab and repeat the process, but then you get a bad request on the add ticket call.

**Comment by skamoen** [comment] 2016-01-17 13:52
That might be another issue. Users can only have one open Order. I corrected this in the ticket-availability-overview branch, but on master you'll get an ImmutableOrderException.

```
        if (order.getStatus().equals(OrderStatus.CREATING)) {

        } else {
            throw new ImmutableOrderException(orderId);
        }
```

**Comment by TimvdLippe** [comment] 2016-01-17 13:56
![image](https://cloud.githubusercontent.com/assets/5948271/12377808/6996ccbe-bd2a-11e5-9cb5-d17bdc4ad6e8.png)

**Comment by TimvdLippe** [comment] 2016-01-17 13:59
The request was failing due to another issue. This has subsequently been fixed, so closing this issue.

**Closed by TimvdLippe** 2016-01-17 13:59 UTC
Labels: help wanted
